{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "service-operator.fullname" . }}-controller-manager-metrics-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "service-operator.labels" . | nindent 4 }}
    control-plane: controller-manager
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "service-operator.selectorLabels" . | nindent 4 }}
    control-plane: controller-manager
{{- end }}